[2023-07-09T19:23:10.072+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Lecture_DAG.python_task manual__2023-07-09T19:23:06.932115+00:00 [queued]>
[2023-07-09T19:23:10.081+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Lecture_DAG.python_task manual__2023-07-09T19:23:06.932115+00:00 [queued]>
[2023-07-09T19:23:10.082+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-09T19:23:10.095+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): python_task> on 2023-07-09 19:23:06.932115+00:00
[2023-07-09T19:23:10.100+0000] {standard_task_runner.py:57} INFO - Started process 464 to run task
[2023-07-09T19:23:10.103+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Lecture_DAG', 'python_task', 'manual__2023-07-09T19:23:06.932115+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/lecture_code.py', '--cfg-path', '/tmp/tmppd30zjph']
[2023-07-09T19:23:10.105+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask python_task
[2023-07-09T19:23:10.148+0000] {task_command.py:410} INFO - Running <TaskInstance: Lecture_DAG.python_task manual__2023-07-09T19:23:06.932115+00:00 [running]> on host bc27030ccba5
[2023-07-09T19:23:10.217+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Lecture_DAG' AIRFLOW_CTX_TASK_ID='python_task' AIRFLOW_CTX_EXECUTION_DATE='2023-07-09T19:23:06.932115+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-09T19:23:06.932115+00:00'
[2023-07-09T19:23:10.234+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/lecture_code.py", line 39, in get_rate
    response = hook.run('v1/bpi/currentprice.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 148, in run
    session = self.get_conn(headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 100, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 434, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `bitcoin_http` isn't defined
[2023-07-09T19:23:10.244+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=Lecture_DAG, task_id=python_task, execution_date=20230709T192306, start_date=20230709T192310, end_date=20230709T192310
[2023-07-09T19:23:10.255+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 12 for task python_task (The conn_id `bitcoin_http` isn't defined; 464)
[2023-07-09T19:23:10.276+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-09T19:23:10.298+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
