[2023-07-11T08:34:01.118+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_sales_4.extract_data_from_api manual__2023-07-11T08:33:58.700826+00:00 [queued]>
[2023-07-11T08:34:01.138+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_sales_4.extract_data_from_api manual__2023-07-11T08:33:58.700826+00:00 [queued]>
[2023-07-11T08:34:01.140+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-11T08:34:01.177+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): extract_data_from_api> on 2023-07-11 08:33:58.700826+00:00
[2023-07-11T08:34:01.186+0000] {standard_task_runner.py:57} INFO - Started process 1214 to run task
[2023-07-11T08:34:01.192+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'process_sales_4', 'extract_data_from_api', 'manual__2023-07-11T08:33:58.700826+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/process_sales_4.py', '--cfg-path', '/tmp/tmp3scuv6ax']
[2023-07-11T08:34:01.193+0000] {standard_task_runner.py:85} INFO - Job 57: Subtask extract_data_from_api
[2023-07-11T08:34:01.278+0000] {task_command.py:410} INFO - Running <TaskInstance: process_sales_4.extract_data_from_api manual__2023-07-11T08:33:58.700826+00:00 [running]> on host ca64464cba28
[2023-07-11T08:34:01.434+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_sales_4' AIRFLOW_CTX_TASK_ID='extract_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2023-07-11T08:33:58.700826+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-11T08:33:58.700826+00:00'
[2023-07-11T08:34:01.439+0000] {logging_mixin.py:149} INFO - 	I'm in get_sales(...) function!
[2023-07-11T08:34:01.687+0000] {logging_mixin.py:149} INFO - Page 1 started
[2023-07-11T08:34:01.690+0000] {logging_mixin.py:149} INFO - Page 1 done
[2023-07-11T08:34:01.691+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-11T08:34:01.851+0000] {logging_mixin.py:149} INFO - Page 2 started
[2023-07-11T08:34:01.855+0000] {logging_mixin.py:149} INFO - Page 2 done
[2023-07-11T08:34:01.856+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-11T08:34:02.016+0000] {logging_mixin.py:149} INFO - Page 3 started
[2023-07-11T08:34:02.019+0000] {logging_mixin.py:149} INFO - Page 3 done
[2023-07-11T08:34:02.020+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-11T08:34:02.179+0000] {logging_mixin.py:149} INFO - Page 4 started
[2023-07-11T08:34:02.180+0000] {logging_mixin.py:149} INFO - Page 4 done
[2023-07-11T08:34:02.181+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-11T08:34:02.352+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ht_template/job1/bll/sales_api.py", line 22, in save_sales_to_local_disk
    json_content.to_csv(f"{raw_dir}/processed_data/{file_name}", index=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 243, in save
    storage_options=self.storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/processed_data/raw/sales/2022-08-09/processed_data/sales_2022-08-09.json'
[2023-07-11T08:34:02.375+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=process_sales_4, task_id=extract_data_from_api, execution_date=20230711T083358, start_date=20230711T083401, end_date=20230711T083402
[2023-07-11T08:34:02.394+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 57 for task extract_data_from_api ([Errno 2] No such file or directory: '/opt/airflow/processed_data/raw/sales/2022-08-09/processed_data/sales_2022-08-09.json'; 1214)
[2023-07-11T08:34:02.446+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-11T08:34:02.466+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
