[2023-07-11T08:46:04.285+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_sales_4.extract_data_from_api manual__2023-07-11T08:46:01.503171+00:00 [queued]>
[2023-07-11T08:46:04.308+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_sales_4.extract_data_from_api manual__2023-07-11T08:46:01.503171+00:00 [queued]>
[2023-07-11T08:46:04.309+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-11T08:46:04.342+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): extract_data_from_api> on 2023-07-11 08:46:01.503171+00:00
[2023-07-11T08:46:04.350+0000] {standard_task_runner.py:57} INFO - Started process 1431 to run task
[2023-07-11T08:46:04.362+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'process_sales_4', 'extract_data_from_api', 'manual__2023-07-11T08:46:01.503171+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/process_sales_4.py', '--cfg-path', '/tmp/tmp6f7uah80']
[2023-07-11T08:46:04.363+0000] {standard_task_runner.py:85} INFO - Job 61: Subtask extract_data_from_api
[2023-07-11T08:46:04.475+0000] {task_command.py:410} INFO - Running <TaskInstance: process_sales_4.extract_data_from_api manual__2023-07-11T08:46:01.503171+00:00 [running]> on host ca64464cba28
[2023-07-11T08:46:05.857+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_sales_4' AIRFLOW_CTX_TASK_ID='extract_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2023-07-11T08:46:01.503171+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-11T08:46:01.503171+00:00'
[2023-07-11T08:46:05.860+0000] {logging_mixin.py:149} INFO - 	I'm in get_sales(...) function!
[2023-07-11T08:46:06.156+0000] {logging_mixin.py:149} INFO - Page 1 started
[2023-07-11T08:46:06.158+0000] {logging_mixin.py:149} INFO - Page 1 done
[2023-07-11T08:46:06.158+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-11T08:46:06.319+0000] {logging_mixin.py:149} INFO - Page 2 started
[2023-07-11T08:46:06.323+0000] {logging_mixin.py:149} INFO - Page 2 done
[2023-07-11T08:46:06.323+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-11T08:46:06.532+0000] {logging_mixin.py:149} INFO - Page 3 started
[2023-07-11T08:46:06.533+0000] {logging_mixin.py:149} INFO - Page 3 done
[2023-07-11T08:46:06.534+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-11T08:46:06.697+0000] {logging_mixin.py:149} INFO - Page 4 started
[2023-07-11T08:46:06.698+0000] {logging_mixin.py:149} INFO - Page 4 done
[2023-07-11T08:46:06.698+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-11T08:46:06.866+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ht_template/job1/bll/sales_api.py", line 23, in save_sales_to_local_disk
    json_content.to_csv(f"{dag_path}/processed_data/raw/sales/2022-08-09/{file_name}", index=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 243, in save
    storage_options=self.storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/processed_data/raw/sales/2022-08-09/sales_2022-08-09.json'
[2023-07-11T08:46:06.885+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=process_sales_4, task_id=extract_data_from_api, execution_date=20230711T084601, start_date=20230711T084604, end_date=20230711T084606
[2023-07-11T08:46:06.905+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 61 for task extract_data_from_api ([Errno 2] No such file or directory: '/opt/airflow/processed_data/raw/sales/2022-08-09/sales_2022-08-09.json'; 1431)
[2023-07-11T08:46:06.943+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-11T08:46:06.960+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
